# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 6) do

  create_table "accounts", :force => true do |t|
    t.column "group_id", :integer, :null => false
    t.column "name",     :string,  :null => false
  end

  add_index "accounts", ["group_id", "name"], :name => "index_accounts_on_group_id_and_name", :unique => true

  create_table "categories", :force => true do |t|
    t.column "group_id", :integer,                               :null => false
    t.column "name",     :string,                                :null => false
    t.column "budget",   :decimal, :precision => 6, :scale => 2
  end

  add_index "categories", ["group_id", "name"], :name => "index_categories_on_group_id_and_name", :unique => true

  create_table "group_user_map", :id => false, :force => true do |t|
    t.column "group_id", :integer, :null => false
    t.column "user_id",  :integer, :null => false
  end

  add_index "group_user_map", ["group_id", "user_id"], :name => "index_group_user_map_on_group_id_and_user_id", :unique => true

  create_table "groups", :force => true do |t|
    t.column "name", :string, :null => false
  end

  add_index "groups", ["name"], :name => "index_groups_on_name", :unique => true

  create_table "money_transactions", :force => true do |t|
    t.column "user_id",     :integer,                                                   :null => false
    t.column "account_id",  :integer,                                                   :null => false
    t.column "category_id", :integer,                                                   :null => false
    t.column "descr",       :string,                                                    :null => false
    t.column "amount",      :decimal,  :precision => 6, :scale => 2,                    :null => false
    t.column "ds",          :date,                                                      :null => false
    t.column "reconciled",  :boolean,                                :default => false, :null => false
    t.column "deleted_at",  :datetime
    t.column "ts",          :datetime,                                                  :null => false
  end

  add_index "money_transactions", ["deleted_at"], :name => "index_money_transactions_on_deleted_at"

  create_table "roles", :force => true do |t|
    t.column "name", :string, :limit => 16, :null => false
  end

  add_index "roles", ["name"], :name => "idx_role_rolename", :unique => true

  create_table "user_roles_map", :id => false, :force => true do |t|
    t.column "role_id", :integer, :null => false
    t.column "user_id", :integer, :null => false
  end

  add_index "user_roles_map", ["role_id", "user_id"], :name => "idx_user_role_map", :unique => true

  create_table "users", :force => true do |t|
    t.column "username", :string, :limit => 16, :null => false
    t.column "name",     :string,               :null => false
    t.column "hash",     :string,               :null => false
  end

  add_index "users", ["username"], :name => "idx_user_username", :unique => true

end
